name: Step 4 - Add Dependabot Version Updates

on:
  push:
    branches:
      - main
    paths:
      - ".github/dependabot.yml"

permissions:
  contents: write
  actions: write
  issues: write

env:
  REVIEW_FILE: ".github/steps/x-review.md"
  DEPENDABOT_FILE: ".github/dependabot.yml"
  DEPENDABOT_KEYPHRASE: "nuget"

jobs:
  find_exercise:
    name: Find Exercise Issue
    if: github.run_number != 1
    uses: skills/exercise-toolkit/.github/workflows/find-exercise-issue.yml@v0.3.0

  check_step_work:
    name: Validate Dependabot Configuration
    needs: find_exercise
    runs-on: ubuntu-latest
    if: "!github.event.repository.is_template"
    env:
      ISSUE_URL: ${{ needs.find_exercise.outputs.issue-url }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Checkout Exercise Toolkit Templates
        uses: actions/checkout@v4
        with:
          repository: skills/exercise-toolkit
          path: exercise-toolkit
          ref: v0.3.0

      - name: Validate 'nuget' Presence in Dependabot Config
        run: |
          file="$DEPENDABOT_FILE"
          keyphrase="$DEPENDABOT_KEYPHRASE"

          if ! grep -q "$keyphrase" "$file"; then
            message="$keyphrase is not present in file $file. Please try again."
            gh issue comment "$ISSUE_URL" \
              --body "$message" \
              --edit-last
            exit 1
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Mark Step as Complete
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file exercise-toolkit/markdown-templates/step-feedback/lesson-review.md \
            --edit-last
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  post_review_content:
    name: Post Review Content
    needs: [find_exercise, check_step_work]
    runs-on: ubuntu-latest
    if: "!github.event.repository.is_template"
    env:
      ISSUE_URL: ${{ needs.find_exercise.outputs.issue-url }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Add Review Feedback to Issue
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file ${{ env.REVIEW_FILE }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  finish_exercise:
    name: Finish Exercise
    needs: [find_exercise, post_review_content]
    uses: skills/exercise-toolkit/.github/workflows/finish-exercise.yml@v0.3.0
    with:
      issue-url: ${{ needs.find_exercise.outputs.issue-url }}

  disable_workflow:
    name: Disable Workflow
    needs: [find_exercise, post_review_content]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Disable This Workflow
        run: gh workflow disable "${{ github.workflow }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
